In [1]:
%pylab inline
%matplotlib inline
import netCDF4 as nc
import xarray as xr
import pylab as plt
import scipy.io
import math
import numpy.matlib
import xlrd
import pandas as pd
from scipy import stats 
import seaborn as sns

Populating the interactive namespace from numpy and matplotlib


In [2]:
ctd_ts_data = pd.read_csv('/Users/Miranda Sitofie/Documents/ctd_ts_data.csv')
ctd_fe_data = pd.read_csv('/Users/Miranda Sitofie/Documents/ctd_fe_data_0.csv')
chl_3day_filter_v5_1999_2020 = xr.open_dataset('/Users/Miranda Sitofie/Documents/chl_3day_filter_v5_1999_2020.nc')

In [3]:
ctd_ts_data

datetime   ctd  Longitude   Latitude     depth    temp  \
0      06/07/2017 03:37  TM01   30.00000 -58.500833     0.999  0.0401   
1      06/07/2017 03:37  TM01   30.00000 -58.500833     1.967 -0.0597   
2      06/07/2017 03:37  TM01   30.00000 -58.500833     2.956 -0.0656   
3      06/07/2017 03:37  TM01   30.00000 -58.500833     3.984 -0.0638   
4      06/07/2017 03:37  TM01   30.00000 -58.500833     4.954 -0.0601   
...                 ...   ...        ...        ...       ...     ...   
20018  10/07/2017 20:20  TM08   29.99967 -41.000167  1483.031  3.4867   
20019  10/07/2017 20:20  TM08   29.99967 -41.000167  1484.016  3.4845   
20020  10/07/2017 20:20  TM08   29.99967 -41.000167  1484.997  3.4888   
20021  10/07/2017 20:20  TM08   29.99967 -41.000167  1485.986  3.5004   
20022  10/07/2017 20:20  TM08   29.99967 -41.000167  1486.979  3.4930   

           sal    oxy      chl  pressure  
0      34.0029  7.434  0.19132         1  
1      34.0002  7.437  0.18135         2  
2      34.0003  7.446  0.17786         3  
3      34.0000  7.440  0.17640         4  
4      34.0005  7.432  0.20149         5  
...        ...    ...      ...       ...  
20018  34.5407  3.560  0.00495      1500  
20019  34.5417  3.560  0.00508      1501  
20020  34.5413  3.564  0.00769      1502  
20021  34.5393  3.564  0.00737      1503  
20022  34.5405  3.561 -0.00006      1504  

[20023 rows x 10 columns]

In [86]:
ctd_ts_data.columns

Index(['datetime', 'ctd', 'Longitude', 'Latitude', 'depth', 'temp', 'sal',
       'oxy', 'chl', 'pressure'],
      dtype='object')

In [87]:
import gsw
gsw.density.rho?

In [88]:
ctd_ts_data['depth'].values

array([9.990000e-01, 1.967000e+00, 2.956000e+00, ..., 1.484997e+03,
       1.485986e+03, 1.486979e+03])

In [89]:
ctd_ts_data['sal'].values

array([34.0029, 34.0002, 34.0003, ..., 34.5413, 34.5393, 34.5405])

In [90]:
ctd_ts_data['temp'].values

array([ 0.0401, -0.0597, -0.0656, ...,  3.4888,  3.5004,  3.493 ])

In [91]:
 ctd_data_density = gsw.density.rho(ctd_ts_data['sal'].values,ctd_ts_data['temp'].values,ctd_ts_data['depth'].values) - 1000

In [92]:
ctd_data_density

array([27.17695626, 27.18447247, 27.18957026, ..., 34.16196033,
       34.16328217, 34.16971083])

In [93]:
ctd_ts_data['Density'] = ctd_data_density
ctd_ts_data

datetime   ctd  Longitude   Latitude     depth    temp  \
0      06/07/2017 03:37  TM01   30.00000 -58.500833     0.999  0.0401   
1      06/07/2017 03:37  TM01   30.00000 -58.500833     1.967 -0.0597   
2      06/07/2017 03:37  TM01   30.00000 -58.500833     2.956 -0.0656   
3      06/07/2017 03:37  TM01   30.00000 -58.500833     3.984 -0.0638   
4      06/07/2017 03:37  TM01   30.00000 -58.500833     4.954 -0.0601   
...                 ...   ...        ...        ...       ...     ...   
20018  10/07/2017 20:20  TM08   29.99967 -41.000167  1483.031  3.4867   
20019  10/07/2017 20:20  TM08   29.99967 -41.000167  1484.016  3.4845   
20020  10/07/2017 20:20  TM08   29.99967 -41.000167  1484.997  3.4888   
20021  10/07/2017 20:20  TM08   29.99967 -41.000167  1485.986  3.5004   
20022  10/07/2017 20:20  TM08   29.99967 -41.000167  1486.979  3.4930   

           sal    oxy      chl  pressure    Density  
0      34.0029  7.434  0.19132         1  27.176956  
1      34.0002  7.437  0.18135         2  27.184472  
2      34.0003  7.446  0.17786         3  27.189570  
3      34.0000  7.440  0.17640         4  27.194148  
4      34.0005  7.432  0.20149         5  27.198995  
...        ...    ...      ...       ...        ...  
20018  34.5407  3.560  0.00495      1500  34.152903  
20019  34.5417  3.560  0.00508      1501  34.158430  
20020  34.5413  3.564  0.00769      1502  34.161960  
20021  34.5393  3.564  0.00737      1503  34.163282  
20022  34.5405  3.561 -0.00006      1504  34.169711  

[20023 rows x 11 columns]

In [94]:
density_mld_reference_10m=ctd_data_density[9] 
density_mld_reference_10m

27.222598050942906

In [41]:
#density_ref = np.where(ctd_data_density == 10)
#density_ref

In [95]:
length_density=len(ctd_data_density)
length_range=np.arange(length_density)

length_range

array([    0,     1,     2, ..., 20020, 20021, 20022])

In [43]:
length_density

20023

In [96]:
mixed_layer_depth_dens = ctd_data_density-density_mld_reference_10m
mixed_layer_depth_dens

array([-0.04564179, -0.03812558, -0.03302779, ...,  6.93936228,
        6.94068411,  6.94711278])

In [97]:
i=mixed_layer_depth_dens<0.031
i

array([ True,  True,  True, ..., False, False, False])

In [98]:
maximum_value = np.max(mixed_layer_depth_dens)
index_maximum_Value = np.where(mixed_layer_depth_dens==maximum_value)
index_maximum_Value


(array([12758], dtype=int64),)

In [99]:
ctd_ts_data.depth[12758]

4179.438

In [118]:
##Second option
mixed_layer_depth_dens[i]=1
mixed_layer_depth_dens

array([1., 1., 1., ..., 0., 0., 0.])

In [119]:
argmax(mixed_layer_depth_dens)

0

In [112]:
mld=mixed_layer_depth_dens>1
a

array([False, False, False, ..., False, False, False])

In [113]:
mixed_layer_depth_dens[mld]=0
mixed_layer_depth_dens

array([1., 1., 1., ..., 0., 0., 0.])

1.0

In [117]:
argmax(maximum_value)


0

In [122]:
for i in length_range:
  mixed_layer_depth_dens = (ctd_data_density.all()-density_mld_reference_10m)
if mixed_layer_depth_dens < 0.031:
 mld=(mixed_layer_depth_dens)/(mixed_layer_depth_dens)  #one returns a mixed depth, true
else:
  mld=0 #zero returns not a mixed depth, false
mld

1.0

In [123]:
argmax(mld)

0

In [1]:
##Question 3: Using the chl_3day_filter_v5_1999_2020 file - plot a mean map of chlorophyll for the Atlantic sector of the Southern

In [12]:
chl_3day_filter_v5_1999_2020

<xarray.Dataset>
Dimensions:  (lon: 1440, lat: 240, time: 1012)
Coordinates:
  * lon      (lon) float64 -180.0 -179.7 -179.5 -179.2 ... 179.3 179.5 179.8
  * lat      (lat) float64 -89.9 -89.65 -89.4 -89.15 ... -30.65 -30.4 -30.15
  * time     (time) datetime64[ns] 1999-01-01 1999-01-09 ... 2020-12-26
Data variables:
    chlor_a  (time, lat, lon) float64 ...

In [6]:
chl_3day_filter_v5_1999_2020.var

<bound method ImplementsDatasetReduce._reduce_method.<locals>.wrapped_func of <xarray.Dataset>
Dimensions:  (lon: 1440, lat: 240, time: 1012)
Coordinates:
  * lon      (lon) float64 -180.0 -179.7 -179.5 -179.2 ... 179.3 179.5 179.8
  * lat      (lat) float64 -89.9 -89.65 -89.4 -89.15 ... -30.65 -30.4 -30.15
  * time     (time) datetime64[ns] 1999-01-01 1999-01-09 ... 2020-12-26
Data variables:
    chlor_a  (time, lat, lon) float64 ...>

In [44]:
chl_3day_filter_v5_1999_2020.time

<xarray.DataArray 'time' (time: 1012)>
array(['1999-01-01T00:00:00.000000000', '1999-01-09T00:00:00.000000000',
       '1999-01-17T00:00:00.000000000', ..., '2020-12-10T00:00:00.000000000',
       '2020-12-18T00:00:00.000000000', '2020-12-26T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 1999-01-01 1999-01-09 ... 2020-12-26
Attributes:
    axis:           T
    standard_name:  time

In [81]:
chl_3day_filter_v5_1999_2020.var

<bound method ImplementsDatasetReduce._reduce_method.<locals>.wrapped_func of <xarray.Dataset>
Dimensions:  (lon: 1440, lat: 240, time: 1012)
Coordinates:
  * lon      (lon) float64 -180.0 -179.7 -179.5 -179.2 ... 179.3 179.5 179.8
  * lat      (lat) float64 -89.9 -89.65 -89.4 -89.15 ... -30.65 -30.4 -30.15
  * time     (time) datetime64[ns] 1999-01-01 1999-01-09 ... 2020-12-26
Data variables:
    chlor_a  (time, lat, lon) float64 ...>

In [29]:
##plotting a mean map of chlorophyll_a
plt.rcParams['font.size'] = 12
plt.figure(figsize=[15,5])
plt.rcParams['lines.linewidth'] = 3
chl_3day_filter_v5_1999_2020.chlor_a.mean.plot(vmin =0,vmax = 1.5,cmap = 'Spectral_r')




SyntaxError: invalid syntax (Temp/ipykernel_9724/1240852415.py, line 5)